name: Automatic build for fedora
on:
  push:
    branches: [ 'gpu_passthrough' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux, x64, fedora]
    steps:
      - name: Checking Out Repository
        uses: actions/checkout@v2
        
      - name: Patching Installers
      - run: |            
          git config user.name "hurrhnn"
          git config user.email "20sunrin022@sunrint.hs.kr"
          
          apt update -y
          apt install wget -y
          
          wget https://gist.githubusercontent.com/hurrhnn/b10f4194fd2729b27946cb472ecaaedb/raw/76fa89169abdefaca86c7fcc26e851073dc89f8d/determine_version.sh
          wget https://gist.githubusercontent.com/hurrhnn/c89ed04c08d193fdfb71ccb0052c7d18/raw/eae9b3e5b7fc75b4c846669a2ed4c64740c10972/installer_patch.sh
          
          ./determine_version.sh
          ./installer_patch.sh
          
      - name: Building Kernels
      - run: |
          ./installer.sh install
      
      - name: Uploading Kernels
        uses: actions/upload-artifact@v3
        with:
          name: linux-tkg-fedora
          path: RPMS/*.rpm
